{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "redisinsight.fullname" . }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: !!str {{ .Values.externalName }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: !!str {{ include "redisinsight.fullname" . }} 
            port:
              number: {{ .Values.service.port }}
{{- end }}
